In [2]:
def read_data(filename):
    """
    Считывает данные из файла, формируя двумерный список.

    Args:
        filename: Имя файла с данными.

    Returns:
        Двумерный список, где каждый подсписок содержит 10 значений.
        Возвращает None, если файл не может быть открыт или формат файла неверен.
    """
    data = []
    current_list = []
    try:
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()  # Удаляем пробелы в начале и конце строки
                if not line:  # Пропускаем пустые строки
                    continue

                try:
                    index, value = line.split('\t')  # Разделяем строку на индекс и значение (разделитель - табуляция)
                    value = float(value)  # Преобразуем значение в число с плавающей точкой
                    current_list.append(value)
                except ValueError:
                    print(f"Ошибка: Неверный формат строки: {line}")
                    return None  # Прерываем чтение файла

                if len(current_list) == 10:
                    data.append(current_list)
                    current_list = []  # Начинаем новый подсписок

        # Проверяем, что количество элементов в последнем списке равно 10 (если есть неполный список)
        if current_list:
            print("Предупреждение: Последний список неполный.")
            #Можно добавить обработку неполного списка, например, дополнить нулями
            data.append(current_list + [0] * (10 - len(current_list)))
            # Или не добавлять его вовсе
            #pass


        return data

    except FileNotFoundError:
        print(f"Ошибка: Файл не найден: {filename}")
        return None
    except Exception as e:
        print(f"Ошибка при чтении файла: {e}")
        return None

In [3]:
def print_mass(mass):
    for row in mass:
        for elem in row:
            print(f"{elem:6.2f}", end = '')
        print()
    

In [4]:
data_temp_all = read_data("decANDsrTutf8.txt")

print_mass(data_temp_all[:-1])
print()

print(data_temp_all[-1])


Предупреждение: Последний список неполный.
 -9.19 -9.60-15.28-13.67-14.23-10.65 -1.22 -4.23 -2.42  0.43
-23.23-11.55 -9.31-15.05 -8.09-12.80  0.27 -0.01 -0.36  3.96
-20.21-16.05-14.86 -2.89  0.64 -0.50 -3.57  0.40  1.36  1.13
 -4.20 -6.30 -9.27-13.53 -6.63 -5.22 -0.84 -3.33 -0.60  2.74
-14.67 -8.91 -9.05 -5.88 -5.18 -5.85 -7.81 -2.51 -1.50  2.78
-11.90-17.46-17.21 -6.70-12.32 -6.92  1.85  0.32  1.00  4.15
-17.67-20.19-15.21 -3.59 -5.42 -7.14  0.60 -0.04  1.10  4.20
-20.59-16.25 -7.40 -8.07 -7.66-12.30 -7.36  0.26  2.71  1.77
 -3.94 -5.96 -6.76-16.32-17.19-15.93 -6.47  1.70  1.45  3.79
 -7.59 -4.45 -5.92 -1.26 -5.43 -3.41 -6.34  2.16  0.27 -0.90
-11.16 -5.23  0.95  0.32  0.01 -4.36  0.23 -0.30  0.22  5.00
 -3.06 -2.89 -4.59 -3.91 -3.82 -2.23  0.55 -0.02  3.72  6.77
 -8.89 -4.56 -9.31 -4.02 -1.15 -2.66 -3.33 -4.82 -1.03  0.28
-12.21 -9.24-16.43-14.74-11.55-14.53 -1.80 -1.44 -0.32  2.52
-10.90 -2.88 -5.49 -9.20 -3.53 -0.81 -1.50 -0.63  1.29  3.61
-11.01  0.81 -3.11 -3.58 -1.66 -3.36 -2.36

In [22]:
temp_diapazon = [-10.45123527,  -6.80335437,  -3.61940009,   0.03310701, 10.]
temp_diapazon[-1] = max(max(data_year))+0.01
data_year = data_temp_all[:-1]
data_temp_pi = data_temp_all[-1][0]

#В каком диапазоне находится данная температура
Temp_in_diap = []
for year in data_year:
    Temp_in_diap_local = []
    for day in year:
        i = 0
        while day >= temp_diapazon[i]:
            i+=1
        Temp_in_diap_local.append(i)
    
    Temp_in_diap.append(Temp_in_diap_local)

# P_m = [[0 for i in temp_diapazon] for i in temp_diapazon]

print_mass(Temp_in_diap)

  1.00  1.00  0.00  0.00  0.00  0.00  3.00  2.00  3.00  4.00
  0.00  0.00  1.00  0.00  1.00  0.00  4.00  3.00  3.00  4.00
  0.00  0.00  0.00  3.00  4.00  3.00  3.00  4.00  4.00  4.00
  2.00  2.00  1.00  0.00  2.00  2.00  3.00  3.00  3.00  4.00
  0.00  1.00  1.00  2.00  2.00  2.00  1.00  3.00  3.00  4.00
  0.00  0.00  0.00  2.00  0.00  1.00  4.00  4.00  4.00  4.00
  0.00  0.00  0.00  3.00  2.00  1.00  4.00  3.00  4.00  4.00
  0.00  0.00  1.00  1.00  1.00  0.00  1.00  4.00  4.00  4.00
  2.00  2.00  2.00  0.00  0.00  0.00  2.00  4.00  4.00  4.00
  1.00  2.00  2.00  3.00  2.00  3.00  2.00  4.00  4.00  3.00
  0.00  2.00  4.00  4.00  3.00  2.00  4.00  3.00  4.00  4.00
  3.00  3.00  2.00  2.00  2.00  3.00  4.00  3.00  4.00  4.00
  1.00  2.00  1.00  2.00  3.00  3.00  3.00  2.00  3.00  4.00
  0.00  1.00  0.00  0.00  0.00  0.00  3.00  3.00  3.00  4.00
  0.00  3.00  2.00  1.00  3.00  3.00  3.00  3.00  4.00  4.00
  0.00  4.00  3.00  3.00  3.00  3.00  3.00  3.00  3.00  4.00
  0.00  0.00  0.00  0.00

In [23]:
#Сколько каких переходов было
Diap = [[0 for i in temp_diapazon] for i in temp_diapazon]
for year in Temp_in_diap:
    for i in range(len(year) - 1):
        Diap[year[i]][year[i+1]] +=1
print_mass(Diap)

#Вероятности переходов = число переходов в этой ячейке / суммарное число переходов в строке
P_m = [[0 for i in temp_diapazon] for i in temp_diapazon]
for i in range(len(temp_diapazon)):
    for j in range((len(temp_diapazon))):
        P_m[i][j] = Diap[i][j] / sum(Diap[i])
print_mass(P_m)

 21.00  8.00  5.00  7.00  2.00
  7.00  4.00  4.00  4.00  3.00
  2.00  7.00 13.00  9.00  5.00
  0.00  0.00 11.00 21.00 18.00
  0.00  0.00  0.00 10.00 19.00
  0.49  0.19  0.12  0.16  0.05
  0.32  0.18  0.18  0.18  0.14
  0.06  0.19  0.36  0.25  0.14
  0.00  0.00  0.22  0.42  0.36
  0.00  0.00  0.00  0.34  0.66


In [24]:
#Определяем матрицу Pi
Pi = [0 for i in temp_diapazon]
i = 0
while data_temp_pi >= temp_diapazon[i]:
    i+=1
Pi[i] = 1
print(Pi)

[0, 1, 0, 0, 0]


In [25]:
def transpon_matr(mass): 
    
    rows = len(mass)
    cols = len(mass[0])

    transposed_matrix = [[0 for _ in range(rows)] for _ in range(cols)]

    # Заполняем транспонированную матрицу
    for i in range(rows):
        for j in range(cols):
            transposed_matrix[j][i] = mass[i][j]

    return transposed_matrix

In [26]:
P_m_t = transpon_matr(P_m)

In [27]:
import numpy as np
Pi_10 = [el for el in Pi]
print(Pi_10)

for i in range(9):
    try:
        Pi_10 = np.dot(np.array(P_m_t), np.array(Pi_10))
        print(Pi_10)
    except np.linalg.LinAlgError:
        print("Матрица A сингулярна (нет решения или бесконечно много решений)")

[0, 1, 0, 0, 0]
[0.31818182 0.18181818 0.18181818 0.18181818 0.13636364]
[0.22334337 0.127608   0.1757123  0.25369502 0.21964131]
[0.15943901 0.09891999 0.16843618 0.28577804 0.28742677]
[0.11869767 0.0804     0.16022022 0.30518914 0.33549296]
[0.09245157 0.0678554  0.15341915 0.31786278 0.36841109]
[0.07526441 0.05936914 0.1484187  0.32628307 0.39066468]
[0.0638927  0.05365626 0.14492398 0.33190226 0.4056248 ]
[0.05632719 0.04982236 0.14253722 0.33565738 0.41565584]
[0.05127993 0.04725366 0.14092468 0.33816816 0.42237356]


In [28]:
print(f"[{-23.86:5.3}; {temp_diapazon[0]:5.3}]: {(Pi_10[0]*100):5.2}%")
for i in range(1, len(temp_diapazon)):
    print(f"[{temp_diapazon[i-1]:5.3}; {temp_diapazon[i]:5.3}]: {(Pi_10[i]*100):5.3}%")

[-23.9; -10.5]:   5.1%
[-10.5;  -6.8]:  4.73%
[ -6.8; -3.62]:  14.1%
[-3.62; 0.0331]:  33.8%
[0.0331;  6.78]:  42.2%
